# Generated by Django 4.2.1 on 2023-05-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_portal.author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(to='app_portal.tag'),
        ),
    ]
